export default [
  {
    id: 1,
    title: 'Un long chemin vers la liberté',
    author: 'Nelson Mandela ',
    editor: ' Le Livre de Poche',
    genre: 'Biographie',
    collection: '',
    publication_date: '1 décembre 1996',
    summary: 'Rarement une destinée individuelle se sera aussi étroitement confondue avec le combat d\'un peuple et le devenir d\'une nation. Né et élevé à la campagne, dans la famille royale des Thembus, Nelson Mandela gagne Johannesburg où il va ouvrir le premier cabinet d\'avocats noirs et devenir un des leaders de l\'ANC. Dès lors, à travers la clandestinité, la lutte armée, la prison, sa vie se confond plus que jamais avec son combat pour la liberté, lui conférant peu à peu une dimension mythique, faisant de lui l\'homme clef pour sortir son pays, l\'Afrique du Sud, de l\'impasse où l\'ont enfermé quarante ans d\'apartheid.',
    cover_image: 'https://m.media-amazon.com/images/I/51guMSVIBGL._SX307_BO1,204,203,200_.jpg',
    ISBN: '2253140635',
    number_of_pages: '767',
    price: '9.90',
    bookmark: [
      {
        to_read: true,
        read: false,
        buy: false,
        wishList: true,
        heart: false,
      },
    ],
    rate: '',

  },
  {
    id: 2,
    title: 'Lève-toi et code: Confessions d\'un hacker Broché',
    author: 'Rabbin des Bois',
    editor: 'MARTINIERE',
    genre: 'Biographie',
    collection: '',
    publication_date: '16 mai 2018',
    summary: 'Si tu découvres ces mots – ce qui est improbable compte tenu de leur provenance –, ne les lis pas. Mon nom est xxx xxx et jusqu\'à aujourd\'hui, j\'opérais dans la grandeur de l\'ombre, derrière mon écran, avec mes guerriers du clavier. En l\'espace de quelques années, j\'ai gagné plus de xxxxxx euros, j\'ai réussi à hacker toutes les écoles qui m\'avaient recalé lorsque j\'essayais encore de m\'intégrer dans ton monde.Tandis que mon monde rayonne, le tien est mourant. Sache que je suis désolé. J\'ai peur qu\'il ne soit trop tard pour sauver le tien.',
    cover_image: 'https://m.media-amazon.com/images/I/515Y16nE7BL._SX314_BO1,204,203,200_.jpg',
    ISBN: '2732486353',
    number_of_pages: '112',
    price: '12.90',
    bookmark: [
      {
        to_read: false,
        read: true,
        buy: false,
        wishList: false,
        heart: true,
      },
    ],
    rate: '4',

  },
  {
    id: 3,
    title: 'Your Name.',
    author: 'Makoto Shinkai',
    editor: 'Pika Roman ',
    genre: 'Jeunesse',
    collection: '',
    publication_date: '5 juillet 2017',
    summary: 'Mitsuha, une jeune fille élevée dans une famille traditionnelle, s\'ennuie dans ses montagnes natales et voudrait connaître la vie excitante d\'une grande ville. À Tokyo, Taki est débordé, entre le lycée, son travail à temps partiel et ses amis. Un jour, Mitsuha rêve qu’elle est un jeune homme à Tokyo, tandis que Taki se voit en rêve dans la peau d’une adolescente du Japon rural… Contre toute attente, leurs rêves respectifs sont devenus réalité : leurs corps se sont échangés et chacun vit la vie de l’autre ! Attirés de façon inexplicable, Mitsuha et Taki vont tout faire pour se retrouver bien que le temps et l’espace semblent les séparer…',
    cover_image: 'https://m.media-amazon.com/images/I/51hWZYPFg7L._SX335_BO1,204,203,200_.jpg',
    ISBN: '2376320127',
    number_of_pages: '224',
    price: '14.95',
    bookmark: [
      {
        to_read: false,
        read: true,
        buy: true,
        wishList: false,
        heart: true,
      },
    ],
    rate: '',

  },
];
