export default [
  {
    id: 1,
    name: 'Durificateur88',
    email: 'dudu88@gmail.com',
    photo: 'https://icons.veryicon.com/png/o/internet--web/prejudice/user-128.png',
    password: 'Dudu88',
    role: 'Membre',
  },
  {
    id: 2,
    name: 'Miguel tchutchuka',
    email: 'migtca@gmail.com',
    photo: 'https://icons.veryicon.com/png/o/internet--web/prejudice/user-128.png',
    password: 'azertyuiop',
    role: 'Membre',
  },
  {
    id: 3,
    name: 'Alban',
    email: 'alban-95@gmail.com',
    photo: 'https://icons.veryicon.com/png/o/internet--web/prejudice/user-128.png',
    password: 'alban95',
    role: 'redacteur',
  },
  {
    id: 4,
    name: 'kenny glb',
    email: 'kennyglb@gmail.com',
    photo: 'https://icons.veryicon.com/png/o/internet--web/prejudice/user-128.png',
    password: 'kmcw94',
    role: 'admin',
  },
  {
    id: 5,
    name: 'Sandy',
    email: 'sandy@gmail.com',
    photo: 'https://icons.veryicon.com/png/o/internet--web/prejudice/user-128.png',
    password: 'sandy',
    role: 'admin',
  },
  {
    id: 6,
    name: 'Laurant F',
    email: 'laurent-f@gmail.com',
    photo: 'https://icons.veryicon.com/png/o/internet--web/prejudice/user-128.png',
    password: 'lolo-f',
    role: 'admin',
  },
  {
    id: 7,
    name: 'Fanette',
    email: 'fanette@gmail.com',
    photo: 'https://icons.veryicon.com/png/o/internet--web/prejudice/user-128.png',
    password: 'fanette',
    role: 'admin',
  },
];
